version: "3.9"
services:
  push1st:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: push1st
    container_name: push1st  
    restart: on-failure
    ports:
      - 6001:6001/tcp
      - 6002:6002/tcp
      - 7001:7001/tcp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./server.yml:/opt/naveksoft/push1st/server.yaml
    networks:
      - default

networks:
  default:
    external:
      name: mediaserver

