app-test:
  name: "Default Application for tests"
  key: "app-key"
  secret: "secret"
  options: { client-messages: true, statistic: false }
  channels: [ public, private, presence, protected ]
  origins: [ "localhost" ]
  hook:
    register: 
      - "*" : http://beam.naveksoft.local/
    unregister: 
      - "*" : http://beam.naveksoft.local/
    join: 
      - "*" : http://beam.naveksoft.local/
      - "va-face-detect-*" : https://beam.naveksoft.local/
    leave: 
      - "*" : http://beam.naveksoft.local/
    push:
      - "*" : http://beam.naveksoft.local/
      - "va-face-detect-*" : https://beam.naveksoft.local/