# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt -y install libyaml-cpp-dev libssl-dev md5deep fakeroot
      - name: Build binaries and upload to nexus
        run: |
          cd push1st-server
          make build=$GITHUB_RUN_NUMBER tag=${GITHUB_REF##*/} all
          curl -s --fail -v -H "Content-Type:multipart/form-data" -vvv -u "uploader:uploader1" --data-binary "@push1st-${GITHUB_REF##*/}.deb" https://nexus.naveksoft.com/repository/ubuntu-universe/
          curl -s --fail -v -u "uploader:uploader1" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-binpush1st-${GITHUB_REF##*/}-latest.tar.bz2
          curl -s --fail -v -u "uploader:uploader1" --upload-file build/naveksoft-beam.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER.tar.bz2
