# This is a basic workflow to help you get started with Actions

name: Ubuntu package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release, dev ]
  pull_request:
    branches: [ main, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set globals
        run: |
            echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
            echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Build
        run: |
            echo $SOURCE_NAME
            echo $SOURCE_BRANCH
            echo $SOURCE_TAG
        env:
            SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
            SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
            SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
#      - name: Install build dependencies
#        run: sudo apt -y install libyaml-cpp-dev libssl-dev lua5.3 liblua5.3-dev md5deep fakeroot
#      - name: Build binaries and upload to nexus
#        run: |
#          cd push1st-server
#          make build=$GITHUB_RUN_NUMBER tag=${GITHUB_REF##*/} all
#          curl -s --fail -v -H "Content-Type:multipart/form-data" -vvv -u "uploader:uploader1" --data-binary "@push1st-${GITHUB_REF##*/}.deb" https://nexus.naveksoft.com/repository/ubuntu-universe/
#          curl -s --fail -v -u "uploader:uploader1" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-latest.tar.bz2
#          curl -s --fail -v -u "uploader:uploader1" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER.tar.bz2
