# This is a basic workflow to help you get started with Actions

name: Ubuntu package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release, dev ]
  pull_request:
    branches: [ main, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-20.04
    runs-on: push1st

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt -y install libyaml-cpp-dev libssl-dev lua5.3 liblua5.3-dev md5deep fakeroot make build-essential python3-pip python3-testresources
      - name: Fetch tags
        run: git fetch -tq
      - name: Build binary
        run: |
          vertag=$(echo `ls -rt .git/refs/tags` | cut -d ' ' -f1)
          cd push1st-server
          make build=$GITHUB_RUN_NUMBER ver=$vertag bname=${GITHUB_REF##*/} all
      - name: Install binary
        run: cd push1st-server && sudo dpkg -i push1st-dev.deb
      - name: Run push1st
        run: |
          /opt/naveksoft/push1st/push1st -c /opt/naveksoft/push1st/server.yml -V3 &
          cd testsuite && pip3 install -r requirements.txt
          python3 testsuite.py
      # - name: Upload binaries to nexus
      #   run: |          
      #     curl -s --fail -v -H "Content-Type:multipart/form-data" -vvv -u "uploader:uploader1" --data-binary "@push1st-${GITHUB_REF##*/}.deb" https://nexus.naveksoft.com/repository/ubuntu-universe/
      #     curl -s --fail -v -u "uploader:uploader1" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-latest.tar.bz2
      #     curl -s --fail -v -u "uploader:uploader1" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER.tar.bz2
