# This is a basic workflow to help you get started with Actions

name: Ubuntu package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ## Sets environment variable
  NEXUS_USER: ${{secrets.NEXUS_USER}}
  NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependencies
        run: sudo apt -y install build-essential libyaml-cpp-dev libssl-dev lua5.3 liblua5.3-dev md5deep fakeroot
      - name: Fetch tags
        run: git fetch -tq
      - name: Build binaries and upload to nexus
        run: |
          vertag=$(echo `ls -rt .git/refs/tags` | cut -d ' ' -f1)
          cd push1st-server
          echo ${GITHUB_REF_NAME}
          make build=$GITHUB_RUN_NUMBER ver=$vertag bname=${GITHUB_REF##*/} all
          curl -s --fail -v -H "Content-Type:multipart/form-data" -vvv -u "${NEXUS_USER}:${NEXUS_PASSWORD}" --data-binary "@push1st-${GITHUB_REF##*/}.deb" https://nexus.naveksoft.com/repository/ubuntu-universe/
          curl -s --fail -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-latest.tar.bz2
          curl -s --fail -v -u "${NEXUS_USER}:${NEXUS_PASSWORD}" --upload-file push1st-${GITHUB_REF##*/}.tar.bz2 https://nexus.naveksoft.com/repository/ubuntu-universe-bin/push1st-${GITHUB_REF##*/}-$GITHUB_RUN_NUMBER.tar.bz2
